<?php

\SequelDash\View::init();

$db = $this->db;

if (!isset($this->query))
	$this->query = (object)array();


$results = null;
if (isset($query->results))
	$results = $query->results;

?>
<div class="query-ui">
	<form action="<?= $this->basePath() ?>/dbs/<?= $db ?>/query" method="post">
		<textarea name="query" class="query-input" placeholder="Query <?= $db ?>..."><?= htmlentities($query->string) ?></textarea>
		<div class="text-right">
			<span style="color:#888;margin-right:1em;position:relative;top:2px;">
				<em ng-bindx="query-status">Showing <?= number_format(count($query->results)) ?> / <?= number_format($query->count) ?> results, from row <?= number_format($query->offset) ?></em>
			</span>
			<button class="execute btn btn-danger">Execute</button>
		</div>
		<br/>
		<div class="query-results-container">
			<? if ($query && $query->string) { ?>
			<div class="alert alert-info">
				Executed query.<br/>

				<? if ($query->table) { ?>
					Table: `<?= $db ?>`.`<?= $query->table ?>`<br/>
				<? } ?>
				<? if ($query->primaryKey) { ?>
					Primary Key: `<?= $query->primaryKey ?>`<br/>
				<? } ?>
			</div>
			<? } ?>
			<table class="query-results">
			<thead>
				<tr>
					<? if ($results) { ?>
						<? 
						$first = $results[0];
						$pkey = $query->primaryKey;

						?>
						<th class="selectAll"><input type="checkbox" name="selectAll" class="selectAll" /></th>
						<? foreach (array_keys($first) as $key) { ?>
							<th><?= $key == $pkey ? '<strong>'.$key.'</strong>' : $key ?></td>
						<? } ?>
						<th class="status"></th>
					<? } else { ?>
						<th></th>
					<? } ?>
				</tr>
			</thead>
			<tbody class="empty">
				<? if ($results) { ?>
					<? foreach ($results as $row) { ?>
						<tr data-id="<?= isset($row[$pkey]) ? $row[$pkey] : '' ?>" data-pkey="<?= $pkey ?>">
						<td class="select"><input type="checkbox" name="selected[]" value="<?= 1 ?>" /></td>
						<? foreach ($row as $k => $v) { ?>
							<? 
								$dv = $v;
								$dv = ($k == $pkey ? '<strong>'.$dv.'</strong>' : $dv); 
							?>
							<td data-value="<?= htmlentities($v) ?>"><span class="trailer" title="<?= htmlentities($v) ?>"><?= $dv ?></span></td>
						<? } ?>
						<td class="status"></td>
						</tr>
					<? } ?>
				<? } else { ?>			
					<tr>
						<td colspan="3" style="text-align:center;">
							<em>No results</em>
						</td>
					</tr>
				<? } ?>
			</tbody>
			<tbody class="data">

			</tbody>
			</table>
		</div>
	</form>
</div>
