<?

use Zend\Captcha;
use Zend\Form\Element;
use Zend\Form\Fieldset;
use Zend\Form\Form;
use Zend\InputFilter\Input;
use Zend\InputFilter\InputFilter;

$model = $this->viewModel()->getCurrent();

?>
<div class="inner jumbotron" style="position:relative;text-align:center;">
    <h1>search: {{table.name}}</h1>

    <? if ($this->error) { ?>
	<br/><br/>
	<span class="alert alert-danger"><?= $this->error ?></span>
	<br/>
	<br/>
    <? } ?>

    <div class="jumbotron-buttons">
    </div>
</div>
<div>

<form action="<?= $this->basePath() ?>/dbs/<?= $this->database['name'] ?>/tables/<?= $this->table['name'] ?>/search" method="post">
<div class="section">
	<table class="data">
	<thead>
		<tr>
		<th style="width:2em;"></th>
		<th style="text-align:right; width:2em;">Field</th>
		<th style="width:5em;"></th>
		<th style="width:auto;">Value</th>
		</tr>
	</thead>
		<? foreach ($this->table['schema'] as $field) { ?>
			<tr>
				<td> 
					&nbsp; <input type="checkbox" class="select" name="select[]" value="<?= $field->name ?>" />
				</td>
				<td style="text-align:right;">
					<?= $field->name ?>
					<br/><span style="opacity:0.5;"><?= $field->type ?></span>
					<? if ($field->default || $field->default === 0) { ?>
						<div class="note note-blue"><?= $field->default ?></div>
					<? } ?>

					<? if ($field->isPrimaryKey) { ?>
						<div class="note note-maroon">PKEY</div>
					<? } else if ($field->isUnique) { ?>
						<div class="note note-orange">UNIQ</div>
					<? } ?>

					<br/><br/>
				</td>				
				<td>
					<select class="operator" name="<?= $field->name ?>[operator]">
						<option>LIKE</option>
						<option>LIKE %...%</option>
						<option>=</option>
						<option>!=</option>
						<option>&gt;</option>
						<option>&gt;=</option>
						<option>&lt;</option>
						<option>&lt;=</option>
						<option>BETWEEN</option>
					</select>
				</td>
				<td>
					<? if ($field->type == 'text' || $field->type == 'longtext') { ?>
						<textarea name="<?= $field->name ?>[value]" style="width:100%;min-height:3em;"></textarea>
					<? } else { ?>
						<div class="one-value">
							<input type="text" name="<?= $field->name ?>[value]" style="width:100%;"  />
						</div>
						<div class="and-value" style="display:none;">
							<input type="text" name="<?= $field->name ?>[start]" /> AND 
							<input type="text" name="<?= $field->name ?>[end]" />
						</div>
					<? } ?>
				</td>
			</tr>	
		<? } ?>
	</table>
	<br/><br/>
	<div style="text-align:center;font-size:125%;">
		<button class="btn btn-success">Go</button>
	</div>
</div>
</form>

<script>
	$(document).ready(function() {
		$('input[type=text], textarea').change(function() {
			var $row = $(this).parents('tr:first');
			var value = true;

			if ($(this).val() == '')
				value = false;

			$row.find('input.select').prop('checked', value).change();
		});

		$('input.select').change(function() {
			var $row = $(this).parents('tr:first');
			if ($(this).is(':checked')) {
				$row.addClass('selected');
			} else {
				$row.removeClass('selected');
			}
		});

		$('select.operator').change(function() {
			var $row = $(this).parents('tr:first');

			if ($(this).val() == 'BETWEEN') {
				$row.find('.one-value').slideUp();
				$row.find('.and-value').slideDown();
			} else { 
				$row.find('.one-value').slideDown();
				$row.find('.and-value').slideUp();

			}
		});
	});
</script>
</div>
<br/>

