<?

use Zend\Captcha;
use Zend\Form\Element;
use Zend\Form\Fieldset;
use Zend\Form\Form;
use Zend\InputFilter\Input;
use Zend\InputFilter\InputFilter;

$model = $this->viewModel()->getCurrent();

?>
<div class="inner jumbotron" style="position:relative;text-align:center;">
    <h1>search: {{table.name}}</h1>

    <? if ($this->error) { ?>
	<br/><br/>
	<span class="alert alert-danger"><?= $this->error ?></span>
	<br/>
	<br/>
    <? } ?>

    <div class="jumbotron-buttons">
    </div>
</div>
<div>

<form action="<?= $this->basePath() ?>/dbs/<?= $this->database['name'] ?>/tables/<?= $this->table['name'] ?>/search" method="post">
<div class="section">
	<table class="data">
	<thead>
		<tr>
		<th style="width:2em;"></th>
		<th style="text-align:right; width:2em;">Field</th>
		<th style="width:5em;"></th>
		<th style="width:auto;">Value</th>
		</tr>
	</thead>
		<? foreach ($this->table['schema'] as $field) { ?>
			<tr>
				<td> 
					&nbsp; <input type="checkbox" class="select" name="select[]" value="<?= $field->name ?>" />
				</td>
				<td style="text-align:right;">
					<?= $field->name ?>
					<br/><span style="opacity:0.5;"><?= $field->type ?></span>
					<? if ($field->default || $field->default === 0) { ?>
						<div class="note note-blue"><?= $field->default ?></div>
					<? } ?>

					<? if ($field->isPrimaryKey) { ?>
						<div class="note note-maroon">PKEY</div>
					<? } else if ($field->isUnique) { ?>
						<div class="note note-orange">UNIQ</div>
					<? } ?>

					<br/><br/>
				</td>				
				<td>
					<select class="operator" name="<?= $field->name ?>[operator]">
						<option>LIKE</option>
						<option>LIKE %...%</option>
						<option>=</option>
						<option>!=</option>
						<option>&gt;</option>
						<option>&gt;=</option>
						<option>&lt;</option>
						<option>&lt;=</option>
						<option>BETWEEN</option>
					</select>
				</td>
				<td class="field" data-name="<?= $field->name ?>">
					<? if ($field->type == 'text' || $field->type == 'longtext') { ?>
						<textarea name="<?= $field->name ?>[value]" style="width:100%;min-height:3em;"></textarea>
					<? } else { ?>
						<div class="one-value">
							<input type="text" name="<?= $field->name ?>[value]" style="width:100%;"  />
						</div>
						<div class="and-value" style="display:none;">
							<input type="text" name="<?= $field->name ?>[start]" /> AND 
							<input type="text" name="<?= $field->name ?>[end]" />
						</div>
					<? } ?>
				</td>
			</tr>	
		<? } ?>
	</table>
	<h2>Preview Query</h2>
	<pre><code class="query-preview language-sql"></code></pre>
	<div style="text-align:center;font-size:125%;">
		<button class="btn btn-success go" type="button" style="font-size:125%;min-width:5em;">Go</button>
		<button class="btn btn-primary query" type="button">Query</button>
	</div>

	<div class="results-container">

	</div>
</div>
</form>

<script>
	$(document).ready(function() {
		var $state = window.$state;
		function generateQuery()
		{
			var criteria = {};
			var table = $state.table.name; 
			var sql = 'SELECT * FROM `'+table+'`';

			var parts = [];

			$('td.field').each(function() {
				var name = $(this).data('name');
				var $field = $('[name=\''+name+'[value]\']');
				var $oper = $('[name=\''+name+'[operator]\']');
				var checked = $(this).parents('tr:first').find('input[type=checkbox]').is(':checked');
				if (!checked)
					return;
				var oper = $oper.val();

				if (oper == 'LIKE %...%') {
					parts.push('`'+name+'` LIKE "%'+$field.val().replace(/"/, '""')+'%"');
					
				} else if (oper == 'BETWEEN') {
					var $start = $('[name=\''+name+'[start]\']');
					var $end = $('[name=\''+name+'[end]\']');

					parts.push('`'+name+'` '+oper+' \"'+$start.val().replace(/"/, '""')+'" '+
							'AND "'+$end.val().replace(/"/, '""')+'"');
				} else {
					parts.push('`'+name+'` '+$oper.val()+' "'+$field.val().replace(/"/, '""')+'"');
				}
			});
			
			if (parts.length > 0) {
				sql += ' WHERE\n';
				sql += '      '+parts.join('\n  AND ')+'\n';
			}

//			queryGenerator.select($state.table, ['*'], criteria);
			return sql;
		}

		function refreshPreview()
		{
			$('.query-preview').html(generateQuery());
			$('.query-preview').each(function() {
				Prism.highlightElement(this);
			});
		}
		
		// TODO: pathing shit
		var basePath = '/sequeldash/app';

		$('button.go').click(function() {
			var query = generateQuery();
			var $state = window.$state;

			// Get 
			$.post(basePath+'/dbs/ns4/query', {
				inline: 1,
				query: query
			}, function(r) {
				$('.results-container').html(r);
				initializeQueryUi($('.results-container .query-ui'));
			});
		});

		$('button.query').click(function() {
			var query = generateQuery();
			var $state = window.$state;
		
			// Off we go!
			// TODO: pathing shit
			$('<form></form>')
				.attr('action', basePath+'/dbs/ns4/tables/'+$state.table.name)
				.attr('method', 'post')
				.html(
					$('<input />')
						.attr('type', 'hidden')
						.attr('name', 'query')
						.val(query)
				)
				.appendTo($('body'))
				.submit();

		});

		$('input[type=text], textarea').change(function() {
			var $row = $(this).parents('tr:first');
			var value = true;

			if ($(this).val() == '')
				value = false;

			$row.find('input.select').prop('checked', value).change();
		});

		var keyTimeout;
		$('input[type=text], textarea').keydown(function() {
			var $row = $(this).parents('tr:first');
			var $area = $(this);
			if (keyTimeout)
				clearTimeout(keyTimeout);

			setTimeout(function() {
				var value = true;

				if ($area.val() == '')
					value = false;

				$row.find('input.select').prop('checked', value).change();
				refreshPreview();

			}, 500);
		});

		$('.operator, input.select').change(function() {
			refreshPreview();
		});

		$('input.select').change(function() {
			var $row = $(this).parents('tr:first');
			if ($(this).is(':checked')) {
				$row.addClass('selected');
			} else {
				$row.removeClass('selected');
			}
		});

		$('select.operator').change(function() {
			var $row = $(this).parents('tr:first');

			if ($(this).val() == 'BETWEEN') {
				$row.find('.one-value').slideUp();
				$row.find('.and-value').slideDown();
			} else { 
				$row.find('.one-value').slideDown();
				$row.find('.and-value').slideUp();

			}
		});
	});
</script>
</div>
<br/>

