<?php 

echo $this->doctype(); 

$deploymentConfigFile = dirname(__FILE__).'/../../../../config/deployment.config.php';
$deployment = (object)array();

if (is_file($deploymentConfigFile)) {
	$deployment = require $deploymentConfigFile;
	$deployment = (object)$deployment;
}

$stage = 'dev';
if (isset($deployment->stage))
	$stage = $deployment->stage;
	
// Zend, we are not off to a good start.
// The next two lines provide access to the primary ViewModel instance, and is also fucktarded.
$viewmodels = $this->viewModel()->getCurrent()->getChildren();
$model = $viewmodels[0];
$request = new stdclass;
$post = new stdclass;

if (isset($model->request)) {
	$rq = $model->request;
	$post = $rq->getPost();
}

if (isset($post->inline)) {
	echo $this->content;
	return;
}

?><html lang="en" 
	ng-app
	ng-init="state.loggedIn=false;startup=true"
>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SequelDash')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))

                        ->prependStylesheet($this->basePath() . '/css/prism.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/platform.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
            

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/platform.min.js')
            ->appendFile($this->basePath() . '/js/ace/ace.js')
	; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
		<div style="float:right;color:white;text-align:right;">
			<div ng-show="startup">Loading...</div>
			<div ng-show="!startup && state.loggedIn">
				{{state.username}}<br/>
				<a href="<?= $this->basePath() ?>/logout">Logout</a>
			</div>
		</div>

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
		    <? if (!isset($model->layout['showLogo']) || $model->layout['showLogo']) { ?>
                    	<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img style="height:1em;" src="<?php echo $this->basePath('img/sequeldash.png') ?>" alt="Zend Framework 2"/>&nbsp;</a>
		    <? } ?>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
			
			<? if (isset($model->breadcrumbs)) foreach ($model->breadcrumbs as $k => $v) { ?>
				<li class="active"><a href="<?= $k ?>"><?= $v ?></a></li>
			<? } ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="content-container">
            <?php echo $this->content; ?>
	    <div style="clear:both;"></div>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> the sequeldash project. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->

	<script type="text/javascript">
		$state = <?= isset($model) ? json_encode((array)$model->getVariables()) : '{na:1}' ?>;
	</script>
        <?php echo $this->inlineScript() ?>
	<? if ($stage == 'dev') { ?>
		<script type="text/javascript" src="<?= $this->basePath() ?>/js/app.js"></script>            
	<? } else { ?>
		<script type="text/javascript" src="<?= $this->basePath() ?>/js/app.min.js"></script>            
	<? } ?>
    </body>
</html>
