<?php 


$deploymentConfigFile = dirname(__FILE__).'/../../../../config/deployment.config.php';
$deployment = (object)array();

if (is_file($deploymentConfigFile)) {
	$deployment = require $deploymentConfigFile;
	$deployment = (object)$deployment;
}

$stage = 'dev';
if (isset($deployment->stage))
	$stage = $deployment->stage;
	
// Zend, we are not off to a good start.
// The next two lines provide access to the primary ViewModel instance, and is also fucktarded.
$viewmodels = $this->viewModel()->getCurrent()->getChildren();
$model = $viewmodels[0];
$request = new stdclass;
$post = new stdclass;

if (isset($model->request)) {
	$rq = $model->request;
	$post = $rq->getPost();
}

if (isset($post->inline)) {
	echo json_encode(array('content' => $this->content, 'model' => isset($model) ? json_encode((array)$model->getVariables()) : new stdclass));
	return;
}

echo $this->doctype(); 
?><html lang="en" 
	ng-init="state.loggedIn=false;startup=true"
>
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('SequelDash')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
					->appendStylesheet($this->basePath() . '/css/platform.css')
					->appendStylesheet($this->basePath() . '/css/style.css')
	; ?>    

	<!-- Scripts -->
	<?php echo $this->headScript()
		->appendFile($this->basePath() . '/js/platform.min.js')
	//	->appendFile($this->basePath() . '/js/ace/ace.js')
	; ?>
	<link href='http://fonts.googleapis.com/css?family=Roboto:300,700,300italic,400italic,100italic,100,400,700italic' rel='stylesheet' type='text/css'>
	<link rel="import" href="<?= $this->basePath() ?>/../components/paper-elements/paper-elements.html" />
	<link rel="import" href="<?= $this->basePath() ?>/../components/core-elements/core-elements.html" />
	<link rel="import" href="<?= $this->basePath() ?>/../components/polymer-ui-card/polymer-ui-card.html" />
	<link rel="import" href="<?= $this->basePath() ?>/../components/ace-element/ace-element.html" />
	<link rel="import" href="<?= $this->basePath() ?>/components/sequeldash.html" />
</head>
<body fullbleed layout vertical unresolved>
	<core-scroll-header-panel condenses flex keepCondensedHeader="true" headerHeight="1200px" condensedheaderheight="60px">
        <core-toolbar layout vertical class="tall <?= isset($model->layoutHero) && $model->layoutHero ? 'hero' : '' ?>">
			<div flex layout horizontal class="top" style="width:100%;">
				<div flex class="mobile-breadcrumbs">
					<paper-menu-button icon="arrow-back" halign="left" valign="top">
						<a ng-repeat="(k, v) in breadcrumbs"
						   href="{{k}}"><paper-item>{{v}}</paper-button></a>
					</paper-menu-button>
				</div>
				<div flex class="breadcrumbs">
					<a href="{{state.basePath}}/"><core-icon-button icon="home"></core-icon-button></a>
					<a ng-repeat="(k, v) in breadcrumbs"
					   href="{{k}}"><paper-button raised>{{v}}</paper-button></a>
				</div>
				<div>
					<span ng-show="startup">Loading...</span>
					<div ng-show="!startup && state.loggedIn" style="display:inline-block;min-width:5em;text-align:right;position:relative;">
						<span id="condensed-logo" style="">
							<span class="loading-indicator"><img class="corner-loading" src="{{state.basePath}}/img/loading.gif" /></span>
							sequeldash | 
						</span>
						<span id="username">
							{{state.username}}
						</span>
					</div>
					<paper-menu-button icon="more-vert" halign="right" valign="top">
						<a href="{{state.basePath}}/about"><paper-item>Manage Users</paper-item></a>
						<a href="{{state.basePath}}/about"><paper-item>About / Updates</paper-item></a>
						<a href="{{state.basePath}}/logout"><paper-item>Logout</paper-item></a>
					</paper-menu-button>
				</div>
			</div>
			
			<!-- // -->
			
			<div layout horizontal flex end class="middle" 
				 style="font-size:100%;width:100%;flex-wrap: wrap;overflow-y:hidden;">
			</div>
			<!-- // -->
			
			<div style="text-align:center;width:100%;" class="bottom">
				<span class="loading-indicator"><img class="logo-loading" src="{{state.basePath}}/img/loading.gif" style="position:relative;top:0.5em;" /></span><br/>
				<div class="logo">
				<? if (!isset($model->layout['showLogo']) || $model->layout['showLogo']) { ?>
					<a href="<?php echo $this->url('home') ?>" style="color:white;">sequeldash</a>
				<? } ?>
				</div>
			</div>
			
		</core-toolbar>
        <div content class="content-container">
            <?php echo $this->content; ?>
	    <div style="clear:both;"></div>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> the sequeldash project. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
	</core-scroll-header-panel>

	<script type="text/javascript">
		$state = <?= isset($model) ? json_encode((array)$model->getVariables()) : '{na:1}' ?>;
	</script>
        <?php echo $this->inlineScript() ?>
	<? if ($stage == 'dev') { ?>
		<script type="text/javascript" src="<?= $this->basePath() ?>/js/app.js"></script>            
	<? } else { ?>
		<script type="text/javascript" src="<?= $this->basePath() ?>/js/app.min.js"></script>            
	<? } ?>

	  <script>
	    // custom transformation: scale header's title
	    var titleStyle = document.querySelector('.logo').style;
	    addEventListener('core-header-transform', function(e) {
	      var d = e.detail;
	      var m = d.height - d.condensedHeight;
		  
	      var scale = Math.max(0.40, (m - d.y) / (m / 0.25)  + 0.40);
	      titleStyle.transform = titleStyle.webkitTransform =
			'scale(' + scale + ') translateZ(0)';

	      $('.logo-loading').css('transform', 'scale('+(scale*2)+') translateZ(0)')
				.css('opacity', (m - d.y) / m);
		  titleStyle.opacity = (m - d.y) / m;
  
  
		  m = 60;
		  var opac = (m - d.y + 30) / (m);
		  opac = Math.max(0, opac);
		  
		  $('core-toolbar .middle').css('opacity', opac);
//		  $('#username').css('opacity', opac);
		  $('#condensed-logo').css('opacity', 1-opac);
	    });

	  </script>
</body>
</html>
