<?
use Zend\Captcha;
use Zend\Form\Element;
use Zend\Form\Fieldset;
use Zend\Form\Form;
use Zend\InputFilter\Input;
use Zend\InputFilter\InputFilter;

\SequelDash\View::init($this);

?>
<div class="meta template-name" data-value="database-details"></div>
<div class="row" style="padding:1em;">
    <div>
        <paper-shadow z="2"></paper-shadow>
        <polymer-ui-card id="databases">
            <div class="card-header">
                <div style="float:right;">
					<ng-filter name="database.tables" within="name"></ng-filter>
					<paper-button raised class="primary navigate" data-href="/dbs/{{database.name}}/query">Query</paper-button>
                </div>
    		<h4>Tables in `{{database.name}}`</h4>
            </div>
            <div class="panel-body">
		<tables-data-view data="{{database}}"></tables-data-view>
	    </div>
	</polymer-ui-card>
    </div>
</div>

<? if (0) { ?>
<table class="data">
<thead>
	<tr>
		<th><sqldash-checkbox name="selectAll" class="selectAll" /></th>
		<th>Name</th>
		<th style="width:2em;">Rows</th>
		<th style="width:5em;">Actions</th>
	</tr>
</thead>
<tbody>
	<tr ng-repeat="table in database.tables">
		<td><sqldash-checkbox name="selectAll" class="selectAll" /></td>
		<td>
			<a href="<?= $this->basePath() ?>/dbs/{{database.name}}/tables/{{table.name}}">{{table.name}}</a>
		</td>
		<td>{{table.rows}}</td>
		<td style="white-space:nowrap;">
			<core-tooltip label="Drop">
				<paper-icon-button icon="delete"></paper-button>
			</core-tooltip>
			<core-tooltip label="Truncate">
				<paper-icon-button icon="clear"></paper-button>
			</core-tooltip>
			<core-tooltip label="Export">
				<paper-icon-button icon="file-download"></paper-button>
			</core-tooltip>
		</td>
	</tr>
</tbody>
</table>
<? } ?>

