<?

?>
<div class="jumbotron clearfix">
    <div class="pull-left col-md-8">
	<h1><?php echo sprintf($this->translate('Welcome to %s'), '<img style="max-width:100%;" src="'.$this->basePath().'/img/sequeldash.png" />') ?></h1>
	<br/>
    </div>
    <div class="col-md-4 pull-right" style="font-size:50%;">
        <div class="panel panel-default" style="position:relative;top:-3.0em;">
            <div class="panel-heading">
		<div style="float:right;"><a href="#" class="btn btn-success">Users</a></div>
                <h3 class="panel-title"><?php echo $this->translate('Service') ?></h3>
            </div>
            <div class="panel-body">
		{{state.service.status}}
		<br/>
		<strong>PID: </strong>{{state.service.pid}}<br/>
		<strong>RAM: </strong>{{state.service.ram}}</span><br/>    		
	    </div>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Recent</h3>
	    </div>
            <div class="panel-body">
            	<em>Coming soon</em>
	    </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">About Sequeldash</h3>
	    </div>
            <div class="panel-body">
		<p><em>You are using Sequeldash, a powerful SQL management application.</em></p>
		<br/>
            	<em>Version 1.0a</em>

		<span class="alert alert-info"><a href="javascript:;">An update is available!</a></span>
	    </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
		<div style="float:right;"><a href="#" class="btn btn-success">Add</a></div>
                <h3 class="panel-title"><?php echo $this->translate('Databases') ?></h3>
            </div>
            <div class="panel-body">
		<div style="float:right">
			<input type="text" class="filter" placeholder="filter" data-filter="databases" />
		</div>
		<table class="data">
		<thead>
			<tr>
				<th><input type="checkbox" name="selectAll" class="selectAll" /></th>
				<th>Name</th>
				<th>Size</th>
			</tr>
		</thead>
		<tbody>
			<tr ng-repeat="db in databases">
				<th><input type="checkbox" name="select[]" value="{{db}}" /></th>
				<td>
					<a href="dbs/{{db}}">{{db}}</a>
				</td>
				<td>
					0 kb
				</td>
			</tr>
		</tbody>
		</table>
            </div>
        </div>
    </div>
</div>
